apiVersion: apps/v1
kind: Deployment
metadata:
  name: wbapp-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: wbapp
  template:
    metadata:
      labels:
        app: wbapp
    spec:
      containers:
      - name: wbapp
        image: 503561452156.dkr.ecr.eu-west-2.amazonaws.com/eks-wboard2-nonprod-euw2:latest
        ports:
        - containerPort: 80