apiVersion: apps/v1
kind: Deployment
metadata:
  name: wbapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wbapp
  template:
    metadata:
      labels:
        app: wbapp
    spec:
      containers:
      - name: wbapp
        image: $(imageUrl) # replace with your Docker image
        ports:
        - containerPort: 80