apiVersion: apps/v1
kind: Deployment
metadata:
  name: wbapp-deployment
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: wbapp
  template:
    metadata:
      labels:
        app: wbapp
    spec:
      containers:
      - name: wbapp
        image: 390402557273.dkr.ecr.eu-west-2.amazonaws.com/eks-wboard-nonprod-euw2:latest 
        ports:
        - containerPort: 9666