#inginx ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-frontend
  namespace: default
  labels:
    name: ingress-frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
    #cert-manager.io/cluster-issuer: letsencrypt  #letsencrypt-staging 
spec:
  tls:
  - hosts:
    - wbapp.test.com
    secretName: letsencrypt #letsencrypt-staging 
  rules:
  - host: wbapp.test.com
    http:
      paths:
      - pathType: Prefix
        path: "/(.*)"
        backend:
          service:
            name: wbapp-service
            port: 
              number: 80
  ingressClassName: nginx