#inginx ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-frontend
spec:
  rules:
  - host: wbapp.test.dv
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: wbapp-service
            port: 
              number: 80
  ingressClassName: nginx
  