name: $(SourceBranchName)-$(Date:yyyyMmdd)$(Rev:.r)
#go
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - deploy
    - src
    - cicd/templates/steps-deploy-tf.yaml
    - cicd/infra-pipeline.yaml
    - cicd/templates/steps-build-push.yaml

pool: 
  vmImage: 'ubuntu-latest'

resources:
- repo: self

variables:
- template: variables/vars-global.yaml
- template: variables/vars-nonprod.yaml

parameters:
- name: environments
  type: object
  default: ['nonprod']
# - name: namespaces
#   type: object
#   default: ['dev']

stages:
- ${{ each env in parameters.environments }}:
  - stage: Deploy_${{ env }}
    displayName: Deploy ${{ env }}
    jobs:
    - job: Deploy_Terraform
      displayName: Deploy terraform infrastructure
      #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
      variables:
      - template: variables/vars-${{ env }}.yaml
      steps:
      - template: templates/steps-deploy-tf.yaml

    - job: Build_Push_Image
      displayName: Build and push docker image
      #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
      steps:
      - template: templates/steps-build-push.yaml
      #task for deploying inginx controller and ingress
      # - template: templates/steps-deploy-nginx-controller.yaml